#- name: common package and configure
#  hosts: sakura-vps
#  vars_files:
#    - vars/password.yml
#  roles:
#    - sakura-root

#- name: common package and configure
#  hosts: sakura-vps
#  roles:
#    - common

- name: make webserver
  sudo: yes
  hosts: sakura-vps
  roles:
    - web

- name: deploy apps
  sudo: yes
  hosts: sakura-vps
  roles:
    - app
