#- name: common package and configure
#  hosts: sakura-vps
#  vars_files:
#    - vars/password.yml
#  roles:
#    - sakura-root

#- name: common package and configure
#  hosts: sakura-vps
#  roles:
#    - common

- name: configure and deploy the webservers and application code
  sudo: yes
  hosts: sakura-vps
  roles:
    - web
