#- name: common package and configure
#  hosts: sakura-vps
#  user: root
#  vars_files:
#    - vars/password.yml
#  roles:
#    - sakura-root

- name: common package and configure
  hosts: sakura-vps
  sudo: yes

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: sakura-vps
  sudo: yes

  roles:
    - web
