#- name: common package and configure
#  hosts: sakura-vps
#  vars_files:
#    - vars/password.yml
#  roles:
#    - sakura-root

- name: server
  sudo: yes
  hosts: sakura-vps
  roles:
    - common
    - web
    - {role: geerlingguy.mysql,
       mysql_root_password: "{{ MYSQL_ROOT_PASSWORD}}" }
    - db
    - app
