---
- name: flaskupload | install python-pip
  yum: name=python-pip state=present

- name: flaskupload | install flask
  command: pip install flask

- name: flaskupload | clone repo
  git: repo=https://github.com/arvelt/flask-fileupload-sample.git dest=/var/www/flaskupload force=yes

- name: flaskupload | chown directory for apache
  file: path=/var/www/flaskupload state=directory owner=apache group=apache recurse=yes

- name: flaskupload | install flaskupload.conf to httpd
  template: src=flaskupload.j2 dest=/etc/httpd/conf.d/flaskupload.conf
  notify:
    - restart httpd
