---
- name: jenkins | get repo
  get_url: url="http://pkg.jenkins-ci.org/redhat/jenkins.repo" dest=/etc/yum.repos.d/jenkins.repo

- name: jenkins | set repo
  command: rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

- name: jenkins | install dependencies JavaSDK
  yum: name=java-1.7.0-openjdk state=present

- name: jenkins | install
  yum: name=jenkins state=present
  notify: restart jenkins

- name: jenkins | change port
  lineinfile: dest=/etc/sysconfig/jenkins regexp="^JENKINS_PORT=" line=JENKINS_PORT="8008"

- name: jenkins | insert iptables rule
  lineinfile: dest=/etc/sysconfig/iptables
              create=yes
              state=present
              insertafter="^:#custom"
              line="-A RH-Firewall-1-INPUT -m state --state NEW -m tcp -p tcp --dport 8008 -j ACCEPT"
  notify: restart iptables
