# install redmine
---
- name: install epel repo
  yum: name=epel-release state=present

- name: required packages
  yum: name={{ item }} state=present
  with_items:
    - libxml2-devel
    - ImageMagick
    - ImageMagick-devel

- name: clone redmine repo
  git: repo=https://github.com/redmine/redmine.git dest=/var/www/redmine version=2.5-stable
  register: redmine_root_dir

- name: who am I
  sudo: no
  command: whoami
  register: current_user

- name: change owner redmine dir
  file: 'path=/var/www/redmine state=directory owner={{current_user.stdout}} group={{current_user.stdout}} recurse=yes'

- name: install redmine database.yml
  sudo: no
  template: src=database.j2 dest=/var/www/redmine/config/database.yml

- name: install bundler
  command: gem install bundler creates=/usr/bin/bundle

- name: install redmine dependence
  sudo: no
  command: bundle install chdir=/var/www/redmine

- name: generate secret token
  sudo: no
  command: rake generate_secret_token chdir=/var/www/redmine

- name: initialise db for redmine
  sudo: no
  command: rake db:migrate RAILS_ENV=production chdir=/var/www/redmine

#- name: create some temp/cache directories | ideally some of the redmine setups should be setup as apache user
#  file: path=$item state=directory
#  with_items:
#    - /var/www/redmine/tmp/cache

- name: chown the redmine directory
  file: path=/var/www/redmine state=directory owner=apache group=apache recurse=yes

# when the first install do following
- name: load default data into redmine
  command: rake redmine:load_default_data RAILS_ENV=production REDMINE_LANG=ja chdir=/var/www/redmine

- name: install redmiine.conf to httpd
  template: src=redmine.j2 dest=/etc/httpd/conf.d/redmine.conf

- name: make symbolic link to use subdirectory
  command: ln -sf /var/www/redmine/public /var/www/html/redmine
  notify:
    - restart httpd
