---
- name: mysql | make owncloud db
  mysql_db: name={{ OWNCLOUD_DB }}

- name: mysql | make owncloud user
  mysql_user: "name={{ OWNCLOUD_USER }} password={{ OWNCLOUD_PASSWORD }} priv={{ OWNCLOUD_DB }}.*:ALL"

- name: mysql | restart
  service: name=mysqld state=restarted
