# Install httpd and Configure
---
- name: httpd | install
  yum: name=httpd state=present
  notify: restart httpd

- name: httpd | insert iptables http rule
  lineinfile: dest=/etc/sysconfig/iptables
              create=yes
              state=present
              insertafter="^:#custom"
              line="-A RH-Firewall-1-INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT"

- name: httpd | insert iptables https rule
  lineinfile: dest=/etc/sysconfig/iptables
              create=yes
              state=present
              insertafter="^:#custom"
              line="-A RH-Firewall-1-INPUT -m state --state NEW -m tcp -p tcp --dport 443 -j ACCEPT"
  notify: restart iptables
