# Install httpd and Configure
---
- name: httpd | install
  yum: name=httpd state=present
  notify: restart httpd

- name: httpd | insert iptables rule
  lineinfile: dest=/etc/sysconfig/iptables
              create=yes
              state=present
              insertafter="^:OUTPUT "
              line="-A INPUT -p tcp  --dport 80 -j  ACCEPT"
  notify: restart iptables
