# install passenger
---
# for centOS6 must be set before sudo gem install
- name: install developer tool for compile passenger
  yum: name={{ item }} state=present
  with_items:
    - gcc-c++
    - zlib-devel
    - curl-devel
    - httpd-devel
    - apr-devel
    - apr-util-devel

- name: enable sudo gem install
  lineinfile: "dest=/etc/sudoers
               state=present
               regexp='^Defaults    secure_path ='
               line='Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'
               validate='visudo -cf %s'"

- name: install passenger
  command: gem install passenger --no-rdoc --no-ri

# - name: install passenger
#   command: gem install passenger --no-rdoc --no-ri executable=/usr/local/bin/gem

- name: find passenger root
  command: passenger-config --root
  register: passenger_root

- name: find passenger module
  stat: path={{ passenger_root.stdout }}/buildout/apache2/mod_passenger.so
  register: module

- name: passenger-module should be installed
  command: "passenger-install-apache2-module --auto --languages=ruby,nodejs"
  when: module.stat.exists != True

- name: get ruby path
  command: which ruby
  register: ruby_dir

- name: httpd should be configured
  template: src=passenger.j2 dest=/etc/httpd/conf.d/passenger.conf
  register: passenger_conf
