# install ruby from source
---
- name: ruby | install developer
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - zlib-devel
    - openssl-devel
    - sqlite
    - sqlite-devel

- name: ruby | download source
  get_url: url="http://cache.ruby-lang.org/pub/ruby/2.0/{{ version }}.tar.gz" dest="./{{ version }}.tar.gz"

- name: ruby | exract
  command: 'tar zxvf {{ version }}.tar.gz creates={{ version }}'

- name: ruby | install
  shell: 'cd {{ version }};{{ item }} creates=/usr/local/bin/ruby'
  with_items:
    - ./configure
    - make
    - make install
